config/routes.rb
Rails.application.routes.draw do
	scope "(:locale)", :locale => /en|de/ do
		root  'pages#index'
		get   'favicon',    to: 'pages#favicon'
		match '/info',      to: 'pages#index',     via: 'get'
		match '/info',      to: 'pages#index',     via: 'post'
		match '/error',     to: 'pages#error',     via: 'get'
		match '/password',  to: 'pages#password',  via: 'get'
		match '/write',     to: 'pages#write',     via: 'post'
	end
end

app/views/pages/error.html.erb
<div class="container">
	<%= t('general.error') %>
</div>

app/views/pages/index.html.erb
<% provide(:title, t('general.title')) %>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a href="#attrib" aria-controls="attrib" role="tab" data-toggle="tab"><%= t('entry.form') %></a></li>
				<li role="presentation"><a href="#raw" aria-controls="raw" role="tab" data-toggle="tab">Raw data</a></li>
			</ul>
			<!-- Tab panes -->
			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="attrib">
					<%= form_with url: write_path, html: { class: "form-horizontal", style: "margin-top: 20px;" }, role: "form" do |form| %>
						<div class="form-group">
							<label for="title" class="col-sm-3 control-label"><%= t('entry.title') %>:</label>
							<div class="col-sm-9">
								<%= form.text_field :title, value: @title, class: "from-control", style: "width: 400px;" %>
							</div>
						</div>
						<div class="form-group">
							<label for="surname" class="col-sm-3 control-label"><%= t('entry.firstname') %>:</label>
							<div class="col-sm-9">
								<%= form.text_field :firstname, value: @firstname, class: "from-control", style: "width: 400px;" %>
							</div>
						</div>
						<div class="form-group">
							<label for="lastname" class="col-sm-3 control-label"><%= t('entry.lastname') %>:</label>
							<div class="col-sm-9">
								<%= form.text_field :lastname, value: @lastname, class: "from-control", style: "width: 400px;" %>
							</div>
						</div>
						<div class="form-group">
							<label for="address" class="col-sm-3 control-label"><%= t('entry.address') %>:</label>
							<div class="col-sm-9">
								<%= form.text_field :address, value: @address, class: "from-control", style: "width: 400px;" %>
							</div>
						</div>
						<div class="form-group">
							<label for="zip_code" class="col-sm-3 control-label"><%= t('entry.zip') %>:</label>
							<div class="col-sm-9">
								<%= form.text_field :zip_code, value: @zip_code, class: "from-control", style: "width: 400px;" %>
							</div>
						</div>
						<div class="form-group">
							<label for="city" class="col-sm-3 control-label"><%= t('entry.city') %>:</label>
							<div class="col-sm-9">
								<%= form.text_field :city, value: @city, class: "from-control", style: "width: 400px;" %>
							</div>
						</div>
						<div class="form-group">
							<label for="mail" class="col-sm-3 control-label"><%= t('entry.mail') %>:</label>
							<div class="col-sm-9">
								<%= form.text_field :mail, value: @mail, class: "from-control", style: "width: 400px;" %>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-offset-3 col-sm-9">
								<%= form.button t('general.save'), class: "btn btn-primary" %>
							</div>
						</div>
					<% end %>
				</div>
				<div role="tabpanel" class="tab-pane" id="raw">
					<pre style="margin: 10px;"><%= @dec_raw %></pre>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/password.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
		    <% flash.each do |message_type, message| %>
		        <div class="alert alert-<%= message_type %>"><%= message %></div>
		    <% end %>
	</div>
	</div>

	<p><%= t('general.enterPassword') %></p>
	<%= form_with url: info_path, role: "form" do |form| %>
		<%= form.hidden_field :PIA_URL, value: @pia_url %>
		<%= form.hidden_field :APP_KEY, value: @app_key %>
		<%= form.hidden_field :APP_SECRET, value: @app_secret %>
		<%= form.password_field :password %>
		<%= form.button t('general.submit') %>
		<div class="form-group" style="margin-left: 20px;">
			<div class="checkbox pull-left" style="margin-bottom: 0;">
				<%= form.check_box :remember, style: "width: inherit;" %>
				<%= t('general.remember') %>
			</div>
		</div>
	<% end %>
</div>